-- INBOX-269 (2026-05-20) — add title + domain columns to alerts table.
--
-- Why we need this:
--   db.create_alert() always writes data["title"] = title, and writes
--   data["domain"] = domain whenever domain is passed (which monitor.py
--   always does). But the prod schema (db/prod-schema-2026-04-22.sql)
--   only has these alerts columns:
--     id, user_id, domain_id, type, severity, message, is_read, created_at
--   So every monitor.py → create_alert() call has been throwing
--     "column 'title' does not exist"
--   which the except Exception: print() handler swallows silently.
--   alerts_created stays at 0, monitor logs "no changes, 0 alerts",
--   and the alerts table has been empty in prod for months.
--
--   The UI + API surface already consume `title` (alerts.html renders
--   it as the headline of each feed row; get_user_alerts() SELECT *
--   returns whatever columns exist). So the fix is to add the columns
--   that the code already expects, not to strip the code.
--
--   Confirmed root cause 2026-05-20 when Vinoop opened /alerts and saw
--   "No alerts in the last 30 days" despite many monitored domains
--   having had score drops, blacklist events, and DNS issues that
--   should have triggered alerts.
--
-- What this fix does NOT do:
--   • Backfill historical alerts — those are unrecoverable. Feed starts
--     populating from the next 15-min monitoring cycle.
--   • Send email/Slack/anything — that's INBOX-144 (Phase 2).
--   • Honour Rules toggles — also INBOX-144 follow-up. Today every
--     detected change creates an alert regardless of user preferences.
--
-- Companion code change (same ticket):
--   • db.create_alert() and adjacent functions replace
--     `print(f"Error ...: {e}")` with `logger.exception("alerts.X")`
--     so the next class of drift surfaces in Sentry instead of stdout.
--   • New tests/test_alerts_create.py — round-trips every alert type
--     through create_alert() → get_user_alerts() to catch schema drift
--     before it ships.
--
-- Idempotent + reversible:
--   • ADD COLUMN IF NOT EXISTS is no-op on subsequent runs.
--   • Also no-op against db/supabase-schema.sql legacy seed, which
--     already declares title + domain on alerts (the seed and the
--     applied-prod-schema diverged at some point — this migration
--     reconciles them).
--   • To reverse: ALTER TABLE public.alerts DROP COLUMN IF EXISTS title;
--     ALTER TABLE public.alerts DROP COLUMN IF EXISTS domain;

-- ─────────────────────────────────────────────────────────────────
-- Add the two columns that db.create_alert() has been trying to write
-- ─────────────────────────────────────────────────────────────────

ALTER TABLE public.alerts ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.alerts ADD COLUMN IF NOT EXISTS domain TEXT;

COMMENT ON COLUMN public.alerts.title IS
    'INBOX-269: short headline rendered as the bold first line of each alert row in /alerts UI. e.g. "Score dropped 12 points" or "Removed from blacklists". Generated by monitor.compare_scan_results() — always non-empty in monitor-originated alerts.';

COMMENT ON COLUMN public.alerts.domain IS
    'INBOX-269: human-readable domain string (e.g. "example.com") for display + filtering convenience. Duplicates what could be looked up via domain_id → domains.domain but avoids the JOIN on the hot /api/user/alerts path. Always set by monitor.py; may be null for alerts created via other surfaces.';
